export const CREATE_FOLDER = "CREATE_FOLDER";
export const GET_FOLDERS = "GET_FOLDERS";
export const SET_LOADING = "SET_LOADING";
export const SET_FOLDER_DETAILS = "SET_FOLDER_DETAILS";
export const FETCH_FOLDER_DETAILS = "FETCH_FOLDER_DETAILS";
